### ISSUE TITLE
Error with "name_list" and "length_list" in datasets

### ISSUE THREAD

**Issue by alireza-soltani** [ChenFengYe/motion-latent-diffusion#53]
Congrats on your great paper!

I am running the "**python demo.py --cfg ./configs/config_mld_humanml3d.yaml --cfg_assets ./configs/assets.yaml --example ./demo/example.txt**" to get demo results on my colab.
First of all, data should be manually downloaded from HumanML3D, because I got the error, stated that Mean.npy and Std.npy doesn't exist. After struggling with that and resolving it with hard code now I got the following error:

!python demo.py --cfg ./configs/config_mld_humanml3d.yaml --cfg_assets ./configs/assets.yaml --example ./demo/example.txt

2023-09-08 07:55:01.073355: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Length-50: a man kicks with something or someone with his left leg.
Length-100: A person is skipping rope.
Length-100: a person walks backward slowly.
Traceback (most recent call last):
  File "/content/demo.py", line 337, in <module>
    main()
  File "/content/demo.py", line 101, in main
    dataset = get_datasets(cfg, logger=logger, phase="test")[0]
  File "/content/mld/data/get_data.py", line 92, in get_datasets
    dataset = dataset_module_map[dataset_name.lower()](
  File "/content/mld/data/HumanML3D.py", line 36, in __init__
    self._sample_set = self.get_sample_set(overrides=sample_overrides)
  File "/content/mld/data/base.py", line 37, in get_sample_set
    return self.Dataset(split_file=split_file, **sample_params)
  File "/content/mld/data/humanml/data/dataset.py", line 357, in __init__
    name_list, length_list = zip(
ValueError: not enough values to unpack (expected 2, got 0)_

Also, when I manually ignore this part, I get an error stating that motion is called before being assigned.

Thank you in advance for your advice.

**Comment by jercas** [comment]
hi! I have also encountered the same problem. Have you solved this problem?

**Comment by santurini** [comment]
Should be solved by unzipping `texts.zip` in `./datasets/humanml3d`

**Comment by yyvhang** [comment]
> Should be solved by unzipping `texts.zip` in `./datasets/humanml3d`

still does not work, this error also exists

**Comment by santurini** [comment]
> still does not work, this error also exists

Can you share how it is structured your folder?

**Comment by yyvhang** [comment]
> > still does not work, this error also exists
> 
> Can you share how it is structured your folder?

I have solved it, thks!

**Comment by zhangjingze21** [comment]
I still have the problem after I unzipped `tests.zip` in `./datasets/humanml3d`, however I still face the problem, could you please tell me how did you solve the problem? Thank you!

**Comment by ZChiWon** [comment]
> I still have the problem after I unzipped `tests.zip` in `./datasets/humanml3d`, however I still face the problem, could you please tell me how did you solve the problem? Thank you!

I have the same problem, need solution plz, thanks!

**Comment by mkstmyk** [comment]
For me, it was solved by downloading [KIT_ML](https://drive.google.com/drive/folders/1MnixfyGfujSP-4t8w_2QvjtTVpEKr97t?usp=sharing), unrar all rar files in it, and update configs/assets.yaml to specify where it is placed as like follows:
```
  HUMANML3D:
    ROOT: '../HumanML3D/KIT-ML/' # HumanML3D directory
    SPLIT_ROOT: '../HumanML3D/KIT-ML/' # HumanML3D splits directory
```

UPDATE:
By using KIT_ML, you may face the known [problem](https://github.com/ChenFengYe/motion-latent-diffusion/issues/26):
I had to download and preprocess correct data from [HumanML3D](https://github.com/EricGuo5513/HumanML3D)
Hope this helps.
